# This Dockerfile is used to build an image containing an node jenkins slave

FROM node:5.12
MAINTAINER Biju Joseph <biju.joseph@semanticbits.com>
RUN npm install -g angular-cli@1.0.0-beta.18 babel typescript typings